### ISSUE TITLE
'preprocess_expansion config.yml' command can not create a file that ends with unique_templates.hdf5

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#28]
Hi. I wanna retrain aizynthfinder by myself based on a part of USPTO datasets. And I have created a CSV file through rdchiral, which has all five mandatory columns. When I set the config.yml well and tried to use the command 'preprocess_expansion', an error was raised below and the unique_templates.hdf5 file was not created: 
2021-03-04 14:51:11.569134: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-04 14:51:11.569341: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Dataset filtered/loaded, generating labels...
Labels created and splitted, generating inputs...
Inputs created and splitted, splitting full Dataset...
Full Dataset splitted, creating unique template set
Traceback (most recent call last):
  File "d:\software\anaconda\lib\site-packages\pandas\core\indexes\base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'classification'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\software\anaconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\software\anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\anaconda\Scripts\preprocess_expansion.exe\__main__.py", line 7, in <module>
  File "d:\software\anaconda\lib\site-packages\aizynthfinder\training\preprocess_expansion.py", line 102, in main
    _save_unique_templates(dataset, config)
  File "d:\software\anaconda\lib\site-packages\aizynthfinder\training\preprocess_expansion.py", line 66, in _save_unique_templates
    dataset["classification"].fillna("-", inplace=True)
  File "d:\software\anaconda\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "d:\software\anaconda\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'classification'

Additionally, my config.yml setting is:
library_headers: ["reaction_hash", "reactants", "products","retro_template", "template_hash","template_code"]
metadata_headers: ["template_hash"]
output_path: "."
file_prefix: "test1"
split_size:
        training: 0.6
        testing: 0.2
        validation: 0.2

Any help would be appreciated.

**Comment by SGenheden** [comment]
Thanks for using the tool @queliyong. I am aware that the tools to create a new policy is less polished and trickier to use, but let's see if we can sort this out.

First, I believe you got another key error from the beginning and you figured out that the solution was to add the "retro_template" column to the library headers. That is hidden "feature" :-) (unfortunately).

Now instead you got a key error on classification, and as you probably noted this shouldn't be mandatory from the documentation - and it shouldn't. But the code that you are using unfortunately makes it mandatory.

 I have therefore made a bugfix and pushed it to master. If you have cloned the repo, you just need to `git pull` to use latest fixes. Otherwise, I believe it is easiest to create a dummy column in your data for "classification".

**Comment by queliyong** [comment]
> Thanks for using the tool @queliyong. I am aware that the tools to create a new policy is less polished and trickier to use, but let's see if we can sort this out.
> 
> First, I believe you got another key error from the beginning and you figured out that the solution was to add the "retro_template" column to the library headers. That is hidden "feature" :-) (unfortunately).
> 
> Now instead you got a key error on classification, and as you probably noted this shouldn't be mandatory from the documentation - and it shouldn't. But the code that you are using unfortunately makes it mandatory.
> 
> I have therefore made a bugfix and pushed it to master. If you have cloned the repo, you just need to `git pull` to use latest fixes. Otherwise, I believe it is easiest to create a dummy column in your data for "classification".

Heartfelt thanks to you for your help!

**Comment by SGenheden** [comment]
@queliyong - did the bugfix solve your problem? can we close the issue?

**Comment by queliyong** [comment]
Yes, it did. Thanks.
