### ISSUE TITLE
ImportError: DLL load failed while importing win32api: The specified program could not be found

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#37]
When I execute the command 'aizynthapp --config config.yml', the jupyter shows 'kernel error' and the following error:

Traceback (most recent call last):
  File "d:\software\anaconda\envs\test\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "d:\software\anaconda\envs\test\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\software\anaconda\envs\test\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "d:\software\anaconda\envs\test\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "d:\software\anaconda\envs\test\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\software\anaconda\envs\test\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "d:\software\anaconda\envs\test\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "d:\software\anaconda\envs\test\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\software\anaconda\envs\test\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "d:\software\anaconda\envs\test\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "d:\software\anaconda\envs\test\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "d:\software\anaconda\envs\test\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "d:\software\anaconda\envs\test\lib\site-packages\jupyter_client\manager.py", line 337, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "d:\software\anaconda\envs\test\lib\site-packages\jupyter_client\manager.py", line 286, in pre_start_kernel
    self.write_connection_file()
  File "d:\software\anaconda\envs\test\lib\site-packages\jupyter_client\connect.py", line 466, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "d:\software\anaconda\envs\test\lib\site-packages\jupyter_client\connect.py", line 136, in write_connection_file
    with secure_write(fname) as f:
  File "d:\software\anaconda\envs\test\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "d:\software\anaconda\envs\test\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "d:\software\anaconda\envs\test\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified program could not be found.

**Comment by dcambie** [comment]
FYI I had the same issue and fixed it by running `Scripts/pywin32_postinstall.py -install` as suggested in jupyter/notebook#4980

**Comment by queliyong** [comment]
> FYI I had the same issue and fixed it by running `Scripts/pywin32_postinstall.py -install` as suggested in [jupyter/notebook#4980](https://github.com/jupyter/notebook/issues/4980)

It works! Thank you very much!
