### ISSUE TITLE
Python kernel do not launch in Jupyter

### ISSUE THREAD

**Issue by mo-be** [MolecularAI/aizynthfinder#43]
Hi,

First of all, I would like to congratulate you for the superb tool you have developped for organic chemists. 

I have hard times launching Python kernel through Jupyter. I don't know why. I am not proficient in coding nor python.
Can you please help me in order to launch Aizynthfinder?

Herein the error message I have when starting Python kernel in Jupyter :
-----------------------------------------------------------------------------------------------------------------------------------
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x00000278AFD9E340>(<Future finis...C: 1\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x00000278AFD9E340>(<Future finis...C: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-9' coro=<HTTP1ServerConnection._server_request_loop() running at C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\tornado\http1connection.py:823> wait_for=<Future finished result=b'GET /kernel...PC: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\tornado\ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_client\manager.py:336>> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x00000278ACB511F0>(<Future finis...C: 1\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x00000278ACB511F0>(<Future finis...C: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-36' coro=<HTTP1ServerConnection._server_request_loop() running at C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\tornado\http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...PC: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\tornado\ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_client\manager.py:336>> is being executed.
[I 20:01:11.760 NotebookApp] Kernel started: 51374adc-d6d5-4612-837b-7c2e68270955, name: python3
Traceback (most recent call last):
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\traitlets\config\application.py", line 844, in launch_instance
    app.initialize(argv)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\traitlets\config\application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\ipykernel\kernelapp.py", line 625, in initialize
    self.write_connection_file()
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\ipykernel\kernelapp.py", line 234, in write_connection_file
    write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_client\connect.py", line 164, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: Le module spécifié est introuvable.
[I 20:01:14.761 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\traitlets\config\application.py", line 844, in launch_instance
    app.initialize(argv)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\traitlets\config\application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\ipykernel\kernelapp.py", line 625, in initialize
    self.write_connection_file()
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\ipykernel\kernelapp.py", line 234, in write_connection_file
    write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_client\connect.py", line 164, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Mo\.conda\envs\aizynth-env\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: Le module spécifié est introuvable.

Thank you in advance,
Mo

**Comment by SGenheden** [comment]
Hello Mo,

This is not an issue with aizynthfinder, but with your particular installation of jupyter. There are probably plenty of suggested solutions out there, this one looks promising: https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

**Comment by mo-be** [comment]
Hi Samuel,

Thank you for your valuable help. I can now start the tool using Jupyter and Python kernel properly installed.
